app.usamoves = [
  {
    name: 'SLAM!',
    reqStrength: 5,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 15,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Slamming the opponent onto the mat and landing on top of them'
  }, {
    name: 'Clothesline',
    reqStrength: 5,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 15,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Classic wrestling move of an arm to the neck! '
  }, {
    name: 'Dropkick',
    reqStrength: 1,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 10,
    staminaCost: 10,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Double kick to the chest or head of someone!'
  }, {
    name: 'Chops / Slaps',
    reqStrength: 3,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 10,
    staminaCost: 10,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Chop / Slap your opponent'
  }, {
    name: 'Punches',
    reqStrength: 2,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 3,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Punch your opponent'
  }, {
    name: 'Kicks',
    reqStrength: 2,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 8,
    staminaCost: 5,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Kick your opponent'
  }, {
    name: 'Miscellaneous',
    reqStrength: 1,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 9,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'brawl',
    decription: ''
  },
  {
    name: 'Stretched submissions',
    reqStrength: 3,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 3,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Arm locks',
    reqStrength: 1,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 8,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 5,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Body locks',
    reqStrength: 4,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 6,
    lustDamage: 0,
    physicalDamage: 20,
    staminaCost: 15,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Leg locks',
    reqStrength: 4,
    reqSpeed: 4,
    reqOrgasm: 0,
    reqSubmission: 2,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Chokes',
    reqStrength: 8,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 6,
    lustDamage: 0,
    physicalDamage: 20,
    staminaCost: 20,
    holdDuration: 3,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Transition holds',
    reqStrength: 3,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 3,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 5,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  }
];
