app.usamoves = [
  {
    name: 'SLAM!',
    reqStrength: 5,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 15,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Slamming the opponent onto the mat and landing on top of them'
  }, {
    name: 'Clothesline',
    reqStrength: 5,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 15,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Classic wrestling move of an arm to the neck! '
  }, {
    name: 'Dropkick',
    reqStrength: 1,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 10,
    staminaCost: 10,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Double kick to the chest or head of someone!'
  }, {
    name: 'Chops / Slaps',
    reqStrength: 3,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 10,
    staminaCost: 10,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Chop / Slap your opponent'
  }, {
    name: 'Punches',
    reqStrength: 2,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 3,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Punch your opponent'
  }, {
    name: 'Kicks',
    reqStrength: 2,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 8,
    staminaCost: 5,
    holdDuration: 0,
    category: 'brawl',
    decription: 'Kick your opponent'
  }, {
    name: 'Miscellaneous',
    reqStrength: 1,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 9,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'brawl',
    decription: ''
  },
  {
    name: 'Stretched submissions',
    reqStrength: 3,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 3,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Arm locks',
    reqStrength: 1,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 8,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 5,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Body locks',
    reqStrength: 4,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 6,
    lustDamage: 0,
    physicalDamage: 20,
    staminaCost: 15,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Leg locks',
    reqStrength: 4,
    reqSpeed: 4,
    reqOrgasm: 0,
    reqSubmission: 2,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 10,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Chokes',
    reqStrength: 8,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 6,
    lustDamage: 0,
    physicalDamage: 20,
    staminaCost: 20,
    holdDuration: 3,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Transition holds',
    reqStrength: 3,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 3,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 5,
    holdDuration: 2,
    category: 'submission',
    decription: ''
  },
  {
    name: 'Pussy fingering',
    reqStrength: 1,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 10,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 2,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Nipple pinching',
    reqStrength: 1,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 5,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 0,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Ass fingering',
    reqStrength: 3,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 10,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 2,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Facesitting',
    reqStrength: 6,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 15,
    physicalDamage: 0,
    staminaCost: 10,
    holdDuration: 3,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'compulsive pussylicking',
    reqStrength: 5,
    reqSpeed: 6,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 15,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 3,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Ass licking',
    reqStrength: 5,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 10,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 2,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Cock stroking',
    reqStrength: 2,
    reqSpeed: 1,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 10,
    physicalDamage: 0,
    staminaCost: 10,
    holdDuration: 2,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Cock sucking',
    reqStrength: 1,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 10,
    physicalDamage: 0,
    staminaCost: 5,
    holdDuration: 2,
    category: 'orgasm',
    decription: ''
  },
  {
    name: 'Arm twist ropewalk chop',
    reqStrength: 1,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 2,
    staminaCost: 5,
    holdDuration: 0,
    category: 'highflying',
    decription: 'The wrestler takes hold of one of the opponent\'s wrists and twists that arm in an arm wrench. The wrestler then climbs up the corner turnbuckles and walks on the top rope, before jumping down and striking the opponent\'s chest, back or the back of their neck. This is often referred to as Old School, the name used by The Undertaker, who popularized it. '
  },
  {
    name: 'Diamond Dust',
    reqStrength: 1,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 15,
    holdDuration: 0,
    category: 'highflying',
    decription: 'This move is a forward somersault three-quarter facelock bulldog/jawbreaker performed by an attacking wrestler from an aerial platform. This move involves the attacking wrestler standing on a platform (i.e. the second turnbuckle, or sitting on the top turnbuckle) and facing the back of a standing opponent while applying an inverted facelock. From this position the attacking wrestler leaps forward, somersaulting, to roll the inverted facelock into a three-quarter facelock, as they fall the wrestler drops to a seated position and driving the opponent\'s jaw into their shoulder for a jawbreaker, or, the wrestler falls back-first forcing the opponent\'s face into the mat/shoulder for the bulldog. This move was innovated by Masato Tanaka. '
  },
  {
    name: 'Diving back elbow drop',
    reqStrength: 1,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 2,
    staminaCost: 5,
    holdDuration: 0,
    category: 'highflying',
    decription: 'This variation of a diving elbow drop sees a wrestler stand facing away from a standing or supine opponent and in an elevated position. The wrestler then dives backwards and strikes the opponent in the shoulder, chest or head with the back of their elbow. '
  },
  {
    name: 'Diving bulldog',
    reqStrength: 1,
    reqSpeed: 5,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 10,
    staminaCost: 20,
    holdDuration: 0,
    category: 'highflying',
    decription: 'This is a bulldog performed by a wrestler from an elevated position. A bulldog is a move in which the wrestler applies a headlock or face lock to his opponent and leaps forward, so that the wrestler lands on his back or in a sitting position, driving the opponent’s face into the mat. A standard diving bulldog sees a wrestler jump down on an opponent from an elevated platform and apply any version of a headlock to take down the opponent to the mat.'
  },
  {
    name: 'Diving Crossbody',
    reqStrength: 1,
    reqSpeed: 6,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 8,
    staminaCost: 15,
    holdDuration: 0,
    category: 'highflying',
    decription: 'This move is used by many, usually light, wrestlers and is often known as a diving crossbody, or a cross body block which is the elevated version of the crossbody maneuver. To perform the move, a wrestler jumps from an elevated position (usually the top turnbuckle) onto an opponent, landing horizontally across the opponent\'s torso, forcing them to the mat and usually resulting in a pinfall attempt. '
  },
  {
    name: 'Diving DDT',
    reqStrength: 1,
    reqSpeed: 7,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 15,
    staminaCost: 25,
    holdDuration: 0,
    category: 'highflying',
    decription: 'The wrestler stands in an elevated position (usually the top rope) and faces the standing or bent-over opponent. As they dive, the wrestler wraps their near arm around the opponent\'s head in a front facelock and swings themselves backwards in midair, landing back-first and simultaneously forcing the opponent\'s head into the mat. '
  },
  {
    name: 'Diving double axe handle',
    reqStrength: 2,
    reqSpeed: 4,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 15,
    holdDuration: 0,
    category: 'highflying',
    decription: 'Also known as a diving axe handle, diving double axe handle smash or diving double sledge, this is accomplished by jumping from the top turnbuckle to the mat or floor and striking the opponent with two fists held together in the fashion of holding an axe. This is usually done on a standing or rising opponent, not a prone one. \n \n A common variation of the diving double axe handle sees the wrestler standing over the top rope, facing away from the ring (facing the fans). From this point, the wrestler jumps and twists his body (from this point, the wrestler would be facing the inside of the ring), and quickly holding both fists together, striking the double axe handle. The maneuver is described as a diving discus (double) axe handle. '
  },
  {
    name: 'Diving elbow drop/pointed elbow drop',
    reqStrength: 1,
    reqSpeed: 4,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 8,
    staminaCost: 15,
    holdDuration: 0,
    category: 'highflying',
    decription: 'A diving elbow drop is executed by diving onto a supine opponent with one\'s elbow cocked, driving the elbow into the opponent\'s shoulder, chest, or head. This move was popularized by Randy Savage, who used it as his finishing move. In a less common variation, known as the diving back elbow drop, the wrestler stands on the top turnbuckle facing away from the opponent then leaps backwards, extending and cocking one elbow. The Undertaker, in his days in World Championship Wrestling as Mean Mark Callous, performed a variation of the diving elbow drop where instead of jumping from the top turnbuckle, he would instead climb up and walk across the ropes before performing the move. \n Pointed elbow drop: The wrestler sits on the top turnbuckle with a foot on each second rope, facing a supine opponent. The wrestler then leaps towards the opponent, clasping their forearms together, and lands on their knees, driving both elbows into the shoulder or chest of the opponent. '
  },
  {
    name: 'Diving fist drop',
    reqStrength: 1,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 2,
    staminaCost: 10,
    holdDuration: 0,
    category: 'highflying',
    decription: 'A fist drop is a move in which a wrestler jumps down from the turnbuckle on an opponent driving his fist into the opponent\'s chest or head. When doing a diving fist drop, wrestlers have their front four knuckles out, and their thumb to the side. '
  },
  {
    name: 'Diving headbutt',
    reqStrength: 1,
    reqSpeed: 3,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 15,
    holdDuration: 0,
    category: 'highflying',
    decription: 'Also known as a diving headbutt drop. A diving headbutt is delivered from the top rope or turnbuckle to anywhere on the opponent\'s body, often the chest. '
  },
  {
    name: 'Diving Hurricarana',
    reqStrength: 1,
    reqSpeed: 6,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 10,
    holdDuration: 0,
    category: 'highflying',
    decription: 'This move is executed by jumping forward off the top rope with legs apart, straddling a standing opponent\'s shoulders, while using the momentum to snap off a hurricanrana. '
  },
  {
    name: 'Dragonrana',
    reqStrength: 1,
    reqSpeed: 6,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 10,
    holdDuration: 0,
    category: 'highflying',
    decription: 'In this variant of the diving hurricanrana, the wrestler first performs a front flip from the top rope before executing a true hurricanrana into a pin. The technique is named by and after the wrestler Dragon Kid, who popularized the maneuver. '
  },
  {
    name: 'Phoenixrana',
    reqStrength: 1,
    reqSpeed: 6,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 10,
    holdDuration: 0,
    category: 'highflying',
    decription: 'With this variant, the wrestler first, facing away from the ring and situated on the top turnbuckle, performs a 180° turn in mid-air and then performs front flip before executing a hurricarana into a pin. '
  },
  {
    name: 'Diving knee drop',
    reqStrength: 1,
    reqSpeed: 2,
    reqOrgasm: 0,
    reqSubmission: 0,
    lustDamage: 0,
    physicalDamage: 5,
    staminaCost: 10,
    holdDuration: 0,
    category: 'highflying',
    decription: 'A move in which a wrestler jumps from a raised platform (the top turnbuckle, the apron, etc.) and lands his or her knee or knees across a supine opponent. There is also a variation where a wrestler jumps from a raised platform and lands his knees across the shoulders of a standing opponent, driving them down to the mat. Melina innovated a version where the attacker jumps and drops two knees into the abdomen of an opponent trapped in the middle ropes in the corner. '
  }
];
